site_name: Lloyd's GitHub Page
site_url: https://lloydmckie-lang.github.io/
site_description: A set of guides to Software Architecture, Career Development, Security, and Sofware Development
site_author: Lloyd
